# Generated by Django 3.1 on 2021-04-01 06:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('cources', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'PYTHON'), ('django', 'Django'), ('java', 'JAVA'), ('node', 'NodeJs'), ('sql', 'SQL'), ('flutter', 'Flutter'), ('react', 'ReactJS')], max_length=20)),
                ('trainer', multiselectfield.db.fields.MultiSelectField(choices=[('manas', 'Manas'), ('james', 'JAMES'), ('nara', 'Narayana'), ('malika', 'Mallika'), ('priti', 'Prithi'), ('Soma', 'Somasekhar'), ('Pr', 'Pratyusha')], max_length=100)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'MORNING'), ('evening', 'EVENING'), ('noon', 'NOON')], max_length=100)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('HYD', 'HYDERABAD'), ('CHE', 'CHENNAI'), ('BANG', 'BANGALORE')], max_length=100)),
            ],
        ),
    ]
