# Generated by Django 3.1 on 2021-04-01 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydata',
            name='gender',
            field=models.CharField(default=datetime.datetime(2021, 4, 1, 6, 32, 3, 901066, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
