# Generated by Django 3.1.7 on 2021-03-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_company'], 'verbose_name_plural': 'Employees'},
        ),
    ]
